# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:                ROLE_USER
        ROLE_SUPER_ADMIN:          ROLE_ADMIN
        ROLE_CLIENT:               ROLE_USER
        ROLE_VETERINAIRE:          ROLE_USER
        ROLE_PROPRIETAIRE_REFUGE:  ROLE_USER
        ROLE_PROPRIETAIRE_MAGASIN: ROLE_USER
        ROLE_DRESSEUR:             ROLE_USER


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
            logout:
                    path:   /Template2
                    target: /affiche
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/afficher, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/affiche/, role: ROLE_CLIENT }
        - { path: ^/admin/, role: ROLE_VETERINAIRE }
        - { path: ^/admin/, role: ROLE_DRESSEUR }



