zanimaux_homepage:
    path:     /
    defaults: { _controller: ZanimauxBundle:Default:index }

affiche:
    path:     /affiche
    defaults: { _controller: ZanimauxBundle:User:affiche }
inscription:
    path:     /inscrit
    defaults: { _controller: ZanimauxBundle:User:inscrit }
redirect:
    path:     /redirect
    defaults: { _controller: ZanimauxBundle:User:redirect }
profile:
    path:     /profile
    defaults: { _controller: ZanimauxBundle:User:show }
deconnexion:
    path:     /Template2
login:
    path:     /log
    defaults: { _controller: ZanimauxBundle:User:login }
loginadmin:
    path:     /dashboard
    defaults: { _controller: ZanimauxBundle:User:adminAffiche }

dresseurpage:
    path:     /dresseur
    defaults: { _controller: ZanimauxBundle:Dresseur:affiche }
delete:
    path:     /delete/{id}
    defaults: { _controller: ZanimauxBundle:User:edit}



